DROP TYPE IF EXISTS categ_culegere;
DROP TYPE IF EXISTS nivel_culegere;
DROP TYPE IF EXISTS format_culegere;

CREATE TYPE categ_culegere AS ENUM('mate', 'info', 'simulari');

CREATE TYPE nivel_culegere AS ENUM(
    'clasa a 12-a m1',
    'clasa a 12-a m2',
    'clasa a 8-a',
    'clasa a 6-a',
    'clasa a 4-a'
);

CREATE TYPE format_culegere AS ENUM('pdf', 'fizic', 'online');


CREATE TABLE IF NOT EXISTS culegeri (
   id serial PRIMARY KEY,
   nume VARCHAR(100) UNIQUE NOT NULL,
   descriere TEXT,
   imagine VARCHAR(300),
   categorie categ_culegere DEFAULT 'mate',
   nivel nivel_culegere DEFAULT 'clasa a 8-a',
   pret NUMERIC(8,2) NOT NULL CHECK (pret >= 0),
   nr_pagini INT NOT NULL CHECK (nr_pagini > 0),
   data_adaugare DATE DEFAULT current_date,
   format format_culegere DEFAULT 'fizic',
   beneficii VARCHAR(300),
   acreditata_minister BOOLEAN NOT NULL DEFAULT FALSE
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'maria') THEN
        CREATE ROLE maria LOGIN PASSWORD 'maria';
    END IF;
END
$$;

GRANT CONNECT ON DATABASE tw2026 TO maria;
GRANT USAGE ON SCHEMA public TO maria;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE culegeri TO maria;
GRANT USAGE, SELECT ON SEQUENCE culegeri_id_seq TO maria;


INSERT INTO culegeri 
(nume, descriere, imagine, categorie, nivel, pret, nr_pagini, data_adaugare, format, beneficii, acreditata_minister) VALUES

('Teste de Matematica pentru Simularea Evaluarii Nationale',
 'Culegere de teste pentru pregatirea simularii la Evaluarea Nationala.',
 '386035.jpg',
 'simulari',
 'clasa a 8-a',
 32.50,
 160,
 '2025-09-10',
 'fizic',
 'are test la final, bareme, rezolvari complete',
 TRUE),

('Matematica Bacalaureat Teste M2',
 'Culegere pentru Bacalaureat la matematica, profil tehnologic M2.',
 '406708.jpg',
 'mate',
 'clasa a 12-a m2',
 39.99,
 220,
 '2025-09-15',
 'fizic',
 'bareme, rezolvari complete',
 FALSE),

('Matematica Ghid complet pentru Evaluarea Nationala',
 'Ghid complet de matematica pentru Evaluarea Nationala, clasa a VIII-a.',
 '407251.jpg',
 'mate',
 'clasa a 8-a',
 45.00,
 240,
 '2025-09-20',
 'fizic',
 'are test la final, rezolvari complete, bareme',
 FALSE),

('Teste de Matematica pentru Simularea Evaluarii Nationale Albastru',
 'Culegere de teste de matematica pentru simularea Evaluarii Nationale.',
 '410705.jpg',
 'simulari',
 'clasa a 8-a',
 31.99,
 150,
 '2025-09-25',
 'fizic',
 'are test la final, bareme',
 TRUE),

('Matematica Teste Rezolvate Bacalaureat',
 'Culegere cu teste rezolvate pentru examenul de Bacalaureat la matematica.',
 '915950184-0.png',
 'mate',
 'clasa a 12-a m1',
 42.00,
 210,
 '2025-10-01',
 'fizic',
 'rezolvari complete, bareme',
 FALSE),

('Bacalaureat Informatica Limbajul C++',
 'Ghid complet de pregatire a examenului de Bacalaureat la informatica, limbajul C++.',
 'Bac_info_coperta_3115-2_1-12.jpg',
 'info',
 'clasa a 12-a m1',
 49.99,
 260,
 '2025-10-05',
 'fizic',
 'rezolvari complete, bareme, suport video',
 TRUE),

('Ghid de Pregatire Informatica Bacalaureat',
 'Culegere de informatica pentru pregatirea examenului de Bacalaureat.',
 'bacalaureat-informatica-intensiv-pascal-c-c-intuneric-ana-sigma_10034190.jpg',
 'info',
 'clasa a 12-a m1',
 44.50,
 230,
 '2025-10-10',
 'fizic',
 'rezolvari complete, teste online',
 FALSE),

('Bacalaureat la Informatica Teste Rezolvate',
 'Culegere de teste rezolvate pentru Bacalaureat la informatica.',
 'bacalaureat-la-informatica-2024-teste-rezolvate-de-antrenament-culegere-de-probleme.jpg',
 'info',
 'clasa a 12-a m1',
 38.99,
 200,
 '2025-10-15',
 'fizic',
 'rezolvari complete, bareme, teste online',
 FALSE),

('Pregatire Bacalaureat Informatica',
 'Material de pregatire pentru Bacalaureat la informatica, conform programei.',
 'c1-pregatire-bacalaureat-informatica-mic.jpg',
 'info',
 'clasa a 12-a m1',
 36.00,
 190,
 '2025-10-20',
 'pdf',
 'rezolvari complete, suport video',
 TRUE),

('Bacalaureat 2026 Matematica',
 'Culegere pentru Bacalaureat la matematica, profil stiinte ale naturii si tehnologic.',
 'coperta_BAC-2024_MATEMATICA_M-Stiintele-naturii_4327-8_1.jpg',
 'mate',
 'clasa a 12-a m2',
 47.99,
 250,
 '2025-10-25',
 'fizic',
 'bareme, rezolvari complete',
 TRUE),

('Evaluare Nationala Clasa a 6-a Matematica si Stiintele Naturii',
 'Culegere pentru pregatirea Evaluarii Nationale la clasa a VI-a.',
 'evaluare-nationala-clasa-6-matematica-si-stiintele-naturii-eduard-dancila-editura-grupul-editorial-art-1.jpg',
 'mate',
 'clasa a 6-a',
 29.99,
 140,
 '2025-11-01',
 'fizic',
 'are test la final, bareme',
 TRUE),

('Matematica Evaluarea Nationala Clasa a VIII-a',
 'Culegere de matematica pentru Evaluarea Nationala, clasa a VIII-a.',
 'evaluarea-nationala-matematica-clasa-a-viii-a-cover_huge.jpg',
 'mate',
 'clasa a 8-a',
 41.50,
 210,
 '2025-11-05',
 'fizic',
 'are test la final, rezolvari complete, bareme',
 FALSE),

('Evaluarea Nationala la finalul clasei a IV-a',
 'Culegere pentru pregatirea Evaluarii Nationale la clasa a IV-a.',
 'GM250-1024x1024.jpg.avif',
 'simulari',
 'clasa a 4-a',
 25.00,
 120,
 '2025-11-10',
 'fizic',
 'are test la final, bareme',
 TRUE),

('Matematica si Stiinte Clasa a 6-a',
 'Culegere pentru clasa a VI-a, matematica si stiinte ale naturii.',
 'images-1.jpeg',
 'mate',
 'clasa a 6-a',
 27.50,
 135,
 '2025-11-15',
 'fizic',
 'are test la final, cartonase',
 FALSE),

('Bacalaureat Matematica Flashcards',
 'Set de cartonase pentru recapitularea rapida a notiunilor de matematica pentru Bacalaureat.',
 'images.jpeg',
 'mate',
 'clasa a 12-a m1',
 59.99,
 100,
 '2025-11-20',
 'fizic',
 'cartonase, suport video',
 FALSE),

('Modele de Subiecte Evaluare Nationala Matematica',
 'Culegere de modele de subiecte pentru pregatirea examenului de Evaluare Nationala.',
 'NKS1679.jpg.webp',
 'simulari',
 'clasa a 8-a',
 34.99,
 170,
 '2025-11-25',
 'pdf',
 'bareme, rezolvari complete',
 FALSE),

('Culegere PDF Matematica',
 'Culegere digitala de matematica pentru pregatire suplimentara.',
 'poze-culegere-pdf_page-0001-scaled-600x777-1.jpg',
 'mate',
 'clasa a 8-a',
 19.99,
 90,
 '2025-12-01',
 'pdf',
 'rezolvari complete, teste online',
 FALSE),

('Simulare Online Matematica Bacalaureat',
 'Simulare online pentru examenul de Bacalaureat la matematica.',
 'res_8b6c75980ad94f0fbacc7ed1c302253f.jpg.avif',
 'simulari',
 'clasa a 12-a m1',
 24.99,
 45,
 '2025-12-05',
 'online',
 'bareme, diploma, teste online',
 FALSE),

('Simulare Online Informatica Bacalaureat',
 'Simulare online pentru examenul de Bacalaureat la informatica.',
 'res_57a420c1ec75347b6bbe3a7f8e2e10a5.jpg.avif',
 'simulari',
 'clasa a 12-a m1',
 29.99,
 50,
 '2025-12-10',
 'online',
 'bareme, diploma, teste online, suport video',
 FALSE),

('Culegere Matematica Evaluare Nationala',
 'Culegere pentru pregatirea Evaluarii Nationale la matematica.',
 'res_450ba56fc87ff9243b23fdc57cfd7c7e.jpg.avif',
 'mate',
 'clasa a 8-a',
 37.99,
 180,
 '2025-12-15',
 'fizic',
 'are test la final, rezolvari complete, bareme',
 TRUE),
 
('Matematica Evaluare Nationala Bacademia',
 'Culegere pentru Evaluarea Nationala la matematica, cu materia sintetizata si exercitii rezolvate.',
 'Screenshot 2026-05-19 at 11.55.26.png',
 'mate',
 'clasa a 8-a',
 54.99,
 220,
 '2025-12-20',
 'fizic',
 'rezolvari complete, suport video, cartonase',
 FALSE),

('Matematica pentru BAC Bacademia',
 'Culegere pentru pregatirea examenului de Bacalaureat la matematica, cu formule colorate si exercitii rezolvate.',
 'Screenshot 2026-05-19 at 11.55.44.png',
 'mate',
 'clasa a 12-a m1',
 59.99,
 250,
 '2025-12-22',
 'fizic',
 'rezolvari complete, bareme, suport video',
 FALSE),

('Informatica C C++ pentru BAC Bacademia',
 'Culegere pentru pregatirea examenului de Bacalaureat la informatica, cu lectii sintetizate si subiecte rezolvate.',
 'Screenshot 2026-05-19 at 11.55.55.png',
 'info',
 'clasa a 12-a m1',
 62.99,
 270,
 '2025-12-24',
 'fizic',
 'rezolvari complete, suport video, teste online',
 FALSE),

('Teste de Matematica Simularea Evaluarii Nationale Verde',
 'Culegere de teste de matematica pentru simularea Evaluarii Nationale, clasa a VIII-a.',
 'Simulare_Evaluare-nationala-8_4377-3_1.jpg',
 'simulari',
 'clasa a 8-a',
 33.99,
 160,
 '2026-01-05',
 'fizic',
 'are test la final, bareme, rezolvari complete',
 TRUE),

('Teste pentru Evaluarea Nationala Clasa a IV-a',
 'Culegere de teste pentru Evaluarea Nationala la clasa a IV-a, la limba romana si matematica.',
 'teste-pentru-evaluarea-nationala-clasa-a-iv-a-limba-si-literatura-romana-matematica-.jpg.png',
 'simulari',
 'clasa a 4-a',
 28.50,
 130,
 '2026-01-10',
 'fizic',
 'are test la final, bareme',
 TRUE),

('Evaluarea Nationala 2025 Clasa a 6-a Matematica si Stiinte',
 'Culegere pentru Evaluarea Nationala la finalul clasei a VI-a, matematica si stiinte.',
 'Unknown.jpeg',
 'simulari',
 'clasa a 6-a',
 30.00,
 145,
 '2026-01-15',
 'fizic',
 'are test la final, bareme, rezolvari complete',
 TRUE);
 